[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.134.3"
  HUGO_ENV = "production" 
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --minify"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.google-analytics.com *.googletagmanager.com *.disqus.com *.disquscdn.com *.jsdelivr.net *.ibruce.info hm.baidu.com *.qhres2.com cse.google.com; style-src 'self' 'unsafe-inline' *.googleapis.com *.jsdelivr.net; img-src 'self' data: *.google-analytics.com *.googletagmanager.com *.aliyuncs.com; font-src 'self' *.googleapis.com *.gstatic.com; connect-src 'self' *.google-analytics.com *.analytics.google.com *.googletagmanager.com;"

# 缓存静态资源
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"  
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 重定向规则（如果需要）
# [[redirects]]
#   from = "/old-path/*"
#   to = "/new-path/:splat"
#   status = 301