[build]
  publish = "public"
  command = "hugo -D"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"
  HUGO_VERSION = "0.89.4"

[context.production.environment]
  HUGO_BASEURL = "https://wwww.onlythinking.com/"

[context.deploy-preview]
  command = "hugo -D -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "*.(css|js|woff|woff2|ttf|png|jpg|jpeg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
